### ISSUE TITLE
image is huge, is this intended?

### ISSUE THREAD

**Issue by szaimen** [cloud-py-api/talk_bot_ai_example#2]
See 
![image](https://github.com/cloud-py-api/talk_bot_ai_example/assets/42591237/0020f47d-e90b-45a4-b71b-7c47eefa565f)

**Comment by szaimen** [comment]
For comparison: 
![image](https://github.com/cloud-py-api/talk_bot_ai_example/assets/42591237/e6f0d8d8-b946-489e-a1c0-329bd55a704c)

**Comment by bigcat88** [comment]
Andrey told me about this, I should look why on x86 image is so big.

Maybe when I will try to switch to Alpine it will gone away and I will not look why in Debian for x86 CPU image there is a problem..

**Comment by bigcat88** [comment]
CUDA...

https://stackoverflow.com/questions/73274526/how-to-integrate-torch-into-a-docker-image-while-keeping-image-size-reasonable

**Comment by szaimen** [comment]
Crazy

**Comment by bigcat88** [comment]
Large size can now be avoided by using separate images for CPU, CUDA and ROCm.
Unfortunately, this is beyond the scope of this example, but it is implemented in `skeleton` app and will be released in the future in context_chat and our other production applications.
