### ISSUE TITLE
Failed to enable ExApp

### ISSUE THREAD

**Issue by andrey18106** [cloud-py-api/talk_bot_ai_example#3]
Last update successfully deploys but fails to enable, looks like small issue on ExApp side.

```Failed to enable ExApp talk_bot_ai_example. Error: list indices must be integers or slices, not str```

Issue appears only if Talk disabled, so that Talk bot APIs not available.

**Comment by bigcat88** [comment]
> Last update successfully deploys but fails to enable, looks like small issue on ExApp side.
> 
> `Failed to enable ExApp talk_bot_ai_example. Error: list indices must be integers or slices, not str`
> 
> Issue appears only if Talk disabled, so that Talk bot APIs not available.

Since these are examples, this is normal, the examples imply simplicity and it is the administrator’s responsibility to make sure that Talk itself is enabled and activated on the server before turning on Talk Bot.
